# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = D:/programs/cmake/bin/cmake.exe

# The command to remove a file.
RM = D:/programs/cmake/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:/GitHub/vehicle_telemetry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:/GitHub/vehicle_telemetry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:/programs/cmake/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:/programs/cmake/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:/GitHub/vehicle_telemetry/CMakeFiles D:/GitHub/vehicle_telemetry//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:/GitHub/vehicle_telemetry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vehicle_telementary

# Build rule for target.
vehicle_telementary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_telementary
.PHONY : vehicle_telementary

# fast build rule for target.
vehicle_telementary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/build
.PHONY : vehicle_telementary/fast

src/classes/car.obj: src/classes/car.cpp.obj
.PHONY : src/classes/car.obj

# target to build an object file
src/classes/car.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/car.cpp.obj
.PHONY : src/classes/car.cpp.obj

src/classes/car.i: src/classes/car.cpp.i
.PHONY : src/classes/car.i

# target to preprocess a source file
src/classes/car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/car.cpp.i
.PHONY : src/classes/car.cpp.i

src/classes/car.s: src/classes/car.cpp.s
.PHONY : src/classes/car.s

# target to generate assembly for a file
src/classes/car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/car.cpp.s
.PHONY : src/classes/car.cpp.s

src/classes/logger.obj: src/classes/logger.cpp.obj
.PHONY : src/classes/logger.obj

# target to build an object file
src/classes/logger.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/logger.cpp.obj
.PHONY : src/classes/logger.cpp.obj

src/classes/logger.i: src/classes/logger.cpp.i
.PHONY : src/classes/logger.i

# target to preprocess a source file
src/classes/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/logger.cpp.i
.PHONY : src/classes/logger.cpp.i

src/classes/logger.s: src/classes/logger.cpp.s
.PHONY : src/classes/logger.s

# target to generate assembly for a file
src/classes/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/logger.cpp.s
.PHONY : src/classes/logger.cpp.s

src/classes/sensor.obj: src/classes/sensor.cpp.obj
.PHONY : src/classes/sensor.obj

# target to build an object file
src/classes/sensor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensor.cpp.obj
.PHONY : src/classes/sensor.cpp.obj

src/classes/sensor.i: src/classes/sensor.cpp.i
.PHONY : src/classes/sensor.i

# target to preprocess a source file
src/classes/sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensor.cpp.i
.PHONY : src/classes/sensor.cpp.i

src/classes/sensor.s: src/classes/sensor.cpp.s
.PHONY : src/classes/sensor.s

# target to generate assembly for a file
src/classes/sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensor.cpp.s
.PHONY : src/classes/sensor.cpp.s

src/classes/sensors/batteryLevel.obj: src/classes/sensors/batteryLevel.cpp.obj
.PHONY : src/classes/sensors/batteryLevel.obj

# target to build an object file
src/classes/sensors/batteryLevel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryLevel.cpp.obj
.PHONY : src/classes/sensors/batteryLevel.cpp.obj

src/classes/sensors/batteryLevel.i: src/classes/sensors/batteryLevel.cpp.i
.PHONY : src/classes/sensors/batteryLevel.i

# target to preprocess a source file
src/classes/sensors/batteryLevel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryLevel.cpp.i
.PHONY : src/classes/sensors/batteryLevel.cpp.i

src/classes/sensors/batteryLevel.s: src/classes/sensors/batteryLevel.cpp.s
.PHONY : src/classes/sensors/batteryLevel.s

# target to generate assembly for a file
src/classes/sensors/batteryLevel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryLevel.cpp.s
.PHONY : src/classes/sensors/batteryLevel.cpp.s

src/classes/sensors/batteryTemp.obj: src/classes/sensors/batteryTemp.cpp.obj
.PHONY : src/classes/sensors/batteryTemp.obj

# target to build an object file
src/classes/sensors/batteryTemp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryTemp.cpp.obj
.PHONY : src/classes/sensors/batteryTemp.cpp.obj

src/classes/sensors/batteryTemp.i: src/classes/sensors/batteryTemp.cpp.i
.PHONY : src/classes/sensors/batteryTemp.i

# target to preprocess a source file
src/classes/sensors/batteryTemp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryTemp.cpp.i
.PHONY : src/classes/sensors/batteryTemp.cpp.i

src/classes/sensors/batteryTemp.s: src/classes/sensors/batteryTemp.cpp.s
.PHONY : src/classes/sensors/batteryTemp.s

# target to generate assembly for a file
src/classes/sensors/batteryTemp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/batteryTemp.cpp.s
.PHONY : src/classes/sensors/batteryTemp.cpp.s

src/classes/sensors/engineTemp.obj: src/classes/sensors/engineTemp.cpp.obj
.PHONY : src/classes/sensors/engineTemp.obj

# target to build an object file
src/classes/sensors/engineTemp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/engineTemp.cpp.obj
.PHONY : src/classes/sensors/engineTemp.cpp.obj

src/classes/sensors/engineTemp.i: src/classes/sensors/engineTemp.cpp.i
.PHONY : src/classes/sensors/engineTemp.i

# target to preprocess a source file
src/classes/sensors/engineTemp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/engineTemp.cpp.i
.PHONY : src/classes/sensors/engineTemp.cpp.i

src/classes/sensors/engineTemp.s: src/classes/sensors/engineTemp.cpp.s
.PHONY : src/classes/sensors/engineTemp.s

# target to generate assembly for a file
src/classes/sensors/engineTemp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/engineTemp.cpp.s
.PHONY : src/classes/sensors/engineTemp.cpp.s

src/classes/sensors/radar.obj: src/classes/sensors/radar.cpp.obj
.PHONY : src/classes/sensors/radar.obj

# target to build an object file
src/classes/sensors/radar.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/radar.cpp.obj
.PHONY : src/classes/sensors/radar.cpp.obj

src/classes/sensors/radar.i: src/classes/sensors/radar.cpp.i
.PHONY : src/classes/sensors/radar.i

# target to preprocess a source file
src/classes/sensors/radar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/radar.cpp.i
.PHONY : src/classes/sensors/radar.cpp.i

src/classes/sensors/radar.s: src/classes/sensors/radar.cpp.s
.PHONY : src/classes/sensors/radar.s

# target to generate assembly for a file
src/classes/sensors/radar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/radar.cpp.s
.PHONY : src/classes/sensors/radar.cpp.s

src/classes/sensors/speed.obj: src/classes/sensors/speed.cpp.obj
.PHONY : src/classes/sensors/speed.obj

# target to build an object file
src/classes/sensors/speed.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/speed.cpp.obj
.PHONY : src/classes/sensors/speed.cpp.obj

src/classes/sensors/speed.i: src/classes/sensors/speed.cpp.i
.PHONY : src/classes/sensors/speed.i

# target to preprocess a source file
src/classes/sensors/speed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/speed.cpp.i
.PHONY : src/classes/sensors/speed.cpp.i

src/classes/sensors/speed.s: src/classes/sensors/speed.cpp.s
.PHONY : src/classes/sensors/speed.s

# target to generate assembly for a file
src/classes/sensors/speed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/classes/sensors/speed.cpp.s
.PHONY : src/classes/sensors/speed.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vehicle_telementary.dir/build.make CMakeFiles/vehicle_telementary.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vehicle_telementary"
	@echo "... src/classes/car.obj"
	@echo "... src/classes/car.i"
	@echo "... src/classes/car.s"
	@echo "... src/classes/logger.obj"
	@echo "... src/classes/logger.i"
	@echo "... src/classes/logger.s"
	@echo "... src/classes/sensor.obj"
	@echo "... src/classes/sensor.i"
	@echo "... src/classes/sensor.s"
	@echo "... src/classes/sensors/batteryLevel.obj"
	@echo "... src/classes/sensors/batteryLevel.i"
	@echo "... src/classes/sensors/batteryLevel.s"
	@echo "... src/classes/sensors/batteryTemp.obj"
	@echo "... src/classes/sensors/batteryTemp.i"
	@echo "... src/classes/sensors/batteryTemp.s"
	@echo "... src/classes/sensors/engineTemp.obj"
	@echo "... src/classes/sensors/engineTemp.i"
	@echo "... src/classes/sensors/engineTemp.s"
	@echo "... src/classes/sensors/radar.obj"
	@echo "... src/classes/sensors/radar.i"
	@echo "... src/classes/sensors/radar.s"
	@echo "... src/classes/sensors/speed.obj"
	@echo "... src/classes/sensors/speed.i"
	@echo "... src/classes/sensors/speed.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

